info:
  contact: {}
  title: EBE3-grupo3
paths:
  /appointments:
    post:
      responses: {}
      summary: create an appointment
      tags:
      - Appointments
  /appointments/{id}:
    get:
      parameters:
      - description: Appointment ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Retrieve an appointment by ID
      tags:
      - Appointments
swagger: "2.0"
